spring:
  datasource:
    username: root
    password: Trigger@1
    url: jdbc:mysql://localhost:3306/springjpa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true